# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'swiftProject' do
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'SwiftDate'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Reusable'
  pod 'ESTabBarController-swift'
  
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  
end

target 'swiftProjectTests' do
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
end
